import test from "node:test"; import assert from "node:assert/strict";
import { assertValidPlan, parseCreatePlanInput, topologicalSort, ValidationError } from "../services/orchestrator/orchestrator.schemas.ts";
import { assertSafeWorkspacePath, redactSecrets, requiredApproval } from "../services/orchestrator/orchestrator.policy.ts";
import type { ExecutionPlan, ExecutionStep } from "../services/orchestrator/orchestrator.types.ts";
import { withTimeout } from "../services/orchestrator/orchestrator.timeout.ts";
import { buildSafeMcpEnvironment } from "../services/mcp/mcp.security.ts";
import { mcpToolId, parseMcpToolId } from "../services/mcp/mcp-tool-id.ts";
import { OrchestratorStore } from "../services/orchestrator/orchestrator.store.ts";
import { unlink } from "node:fs/promises";
import path from "node:path";
const step=(id:string,dependsOn:string[]=[],toolId="system.summarize"):ExecutionStep=>({id,title:id,description:id,toolId,arguments:{},dependsOn,status:"pending",approvalMode:"never",retryCount:0,maxRetries:2});
const plan=(steps:ExecutionStep[]):ExecutionPlan=>({id:"plan",objective:"objetivo válido",summary:"resumo",skillIds:["general.execute-goal"],status:"awaiting_approval",steps,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
test("valida entrada de criação",()=>assert.deepEqual(parseCreatePlanInput({objective:"  pesquisar IA  ",skillId:"auto"}),{objective:"pesquisar IA",skillId:"auto"}));
test("rejeita objetivo inválido",()=>assert.throws(()=>parseCreatePlanInput({objective:"x"}),ValidationError));
test("ordena etapas por dependência",()=>assert.deepEqual(topologicalSort([step("c",["b"]),step("a"),step("b",["a"])]).map((s)=>s.id),["a","b","c"]));
test("detecta dependência circular",()=>assert.throws(()=>topologicalSort([step("a",["b"]),step("b",["a"])]),/circular/));
test("bloqueia ferramenta inexistente",()=>assert.throws(()=>assertValidPlan(plan([step("a",[],"missing")]),new Set(["system.summarize"])),/inexistente/));
test("aceita plano válido",()=>assert.doesNotThrow(()=>assertValidPlan(plan([step("a")]),new Set(["system.summarize"]))));
test("ferramenta destrutiva exige aprovação por etapa",()=>assert.equal(requiredApproval("destructive","never"),"step"));
test("efeito externo exige aprovação por etapa",()=>assert.equal(requiredApproval("external","plan"),"step"));
test("escrita aparece no plano aprovado",()=>assert.equal(requiredApproval("write","never"),"plan"));
test("leitura preserva política declarada",()=>assert.equal(requiredApproval("read","never"),"never"));
test("redige segredos",()=>{const value=redactSecrets("api_key=abc123 token: xyz987 password=qwerty");assert.equal(value.includes("abc123"),false);assert.equal(value.includes("xyz987"),false);assert.equal(value.includes("qwerty"),false);});
test("bloqueia directory traversal",()=>assert.throws(()=>assertSafeWorkspacePath("../segredo",process.cwd()),/fora da raiz/));
test("aceita caminho dentro da raiz",()=>assert.match(assertSafeWorkspacePath(".generated/a.json",process.cwd()),/\.generated/));
test("aplica timeout",async()=>await assert.rejects(withTimeout(new Promise(()=>{}),5),/Timeout/));
test("MCP herda somente allowlist e env explícito",()=>{const env=buildSafeMcpEnvironment({CUSTOM:"ok"},{PATH:"bin",SECRET_TOKEN:"não",HOME:"home"});assert.deepEqual(env,{PATH:"bin",HOME:"home",CUSTOM:"ok"});});
test("normaliza e interpreta ferramenta MCP",()=>assert.deepEqual(parseMcpToolId(mcpToolId("server-1","search.web")),{serverId:"server-1",toolName:"search.web"}));
test("rejeita identificador MCP inseguro",()=>assert.throws(()=>mcpToolId("../server","tool"),/inválido/));
test("recupera execução interrompida como pausada sem repetir etapa concluída",async()=>{const store=new OrchestratorStore();const id=crypto.randomUUID();const now=new Date().toISOString();await store.saveRun({id,planId:crypto.randomUUID(),status:"running",steps:[{...step("done"),status:"completed"},{...step("active"),status:"running"}],createdAt:now,updatedAt:now,callCount:1});await store.recoverInterruptedRuns();const recovered=await store.getRun(id);assert.equal(recovered?.status,"paused");assert.equal(recovered?.steps[0].status,"completed");assert.equal(recovered?.steps[1].status,"pending");await unlink(path.join(process.cwd(),".generated","orchestrator","runs",`${id}.json`));});
